### ISSUE TITLE
error code 404 during update

### ISSUE THREAD

**Issue by lybserv** [GoldenGnu/jeveassets#318]
getting 404 errors during updating assets.

any hint?

**Comment by GoldenGnu** [comment]
Yes, all the ESI assets endpoints have been down for the last 24 hours. This is a CCP issue. They are aware they of the problem. So, all we can do is wait for CCP to fix it…

**Comment by lybserv** [comment]
thanks for the fast reply!

**Comment by GoldenGnu** [comment]
this should be resolved now, please, comment on the issues, if you're still getting erros

**Comment by lybserv** [comment]
it was fixed for a few hours, now its 404 again

**Comment by FlowDrucka64** [comment]
I am still getting 
ESI > Assets > <Char name>
Error Code: 404
{"error":"Not found}

when trying to update

This error has persisted for the last 3 days at least (didnt try before)

**Comment by GoldenGnu** [comment]
Yes, the asset endpoints are offline, again:
https://github.com/esi/esi-issues/issues/1319
